FROM maven:3.9.9-eclipse-temurin-17 AS builder
WORKDIR /build
COPY pom.xml ./pom.xml
COPY eureka-server ./eureka-server
COPY gateway-service ./gateway-service
COPY vehiculos-service ./vehiculos-service
COPY operaciones-service ./operaciones-service
RUN mvn -B -pl eureka-server -am -DskipTests clean package

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /build/eureka-server/target/*.jar app.jar
EXPOSE 8761
ENTRYPOINT ["java", "-jar", "app.jar"]
