FROM maven:3.9.9-eclipse-temurin-17 AS builder
WORKDIR /build
COPY pom.xml ./pom.xml
COPY eureka-server ./eureka-server
COPY gateway-service ./gateway-service
COPY vehiculos-service ./vehiculos-service
COPY operaciones-service ./operaciones-service
RUN mvn -B -pl vehiculos-service -am -DskipTests clean package

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /build/vehiculos-service/target/*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
